from __future__ import annotations

from typing import Tuple


def args_to_typehints(argument) -> Tuple[str, str]:
    """This function holds all unique argument occurences found throughout
    the autodesk documentation.  If any new styles are found in the future,
    updating the table below should account for the new additions."""
    lookup_table = {"boolean": ["bool",
                                "bool"],
                    "string": ["str",
                               "str"],
                    "int": ["int",
                            "int"],
                    "float": ["float",
                              "float"],
                    "uint": ["int",
                             "int"],
                    "[float, float, float]": ["Tuple[float, float, float]",
                                              "(float, float, float)"],
                    "name": ["str",
                             "str"],
                    "linear": ["float",
                               "float"],
                    "[linear, linear, linear]": ["Tuple[float, float, float]",
                                                 "[float, float, float]"],
                    "angle": ["float",
                              "float"],
                    "[angle, angle, angle]": ["Tuple[float, float, float]",
                                              "[float, float, float]"],
                    "script": ["str",
                               "str"],
                    "time": ["Union[float, Tuple[float, float]]",
                             "[float, float]"],
                    "[float, float]": ["Tuple[float, float]",
                                       "[float, float]"],
                    "[float, float, float, float]": ["Tuple[float, float, float, float]",
                                                     "[float, float, float, float]"],
                    "[name, string]": ["Tuple[str, str]",
                                       "[str, str]"],
                    "[int, string]": ["Tuple[int, str]",
                                      "[int, str]"],
                    "[string, string]": ["Tuple[str, str]",
                                         "[str, str]"],
                    "[string, string, string]": ["Tuple[str, str, str]",
                                                 "[str, str, str]"],
                    "[string, string, string, string]": ["Tuple[str, str, str, str]",
                                                         "[str, str, str]"],
                    "[string, string, string, string, string]": ["Tuple[str, str, str, str, str]",
                                                                 "[str, str, str, str, str]"],
                    "[string, string, string, string, string, string]": ["Tuple[str, str, str, str, str, str]",
                                                                         "[str, str, str, str, str, str]"],
                    "[int, string, int]": ["Tuple[int, str, int]",
                                           "[int, str, int]"],
                    "[int, int]": ["Tuple[int, int]",
                                   "[int, int]"],
                    "[int, int, int]": ["Tuple[int, int, int]",
                                        "[int, int, int]"],
                    "[int, int, int, int]": ["Tuple[int, int, int, int]",
                                             "[int, int, int, int]"],
                    "[int, int, int, int, int]": ["Tuple[int, int, int, int, int]",
                                                  "[int, int, int, int, int]"],
                    "[int, int, int, int, int, int]": ["Tuple[int, int, int, int, int, int]",
                                                       "[int, int, int, int, int, int]"],
                    "[uint, uint]": ["Tuple[int, int]",
                                     "[int, int]"],
                    "timerange": ["Tuple[float, float]",
                                  "[float, float]"],
                    "string[]": ["Listt[str]",
                                 "[str]"],
                    "floatrange": ["Tuple[float, float]",
                                   "[float, float]"],
                    "[[, boolean, float, ]]": ["List[Union[bool, float]]",
                                               "[float]"],
                    "[uint, uint, uint]": ["Tuple[int, int, int]",
                                           "[int, int, int]"],
                    "[uint, uint, uint, uint]": ["Tuple[int, int, int, int]",
                                                 "[int, int, int, int]"],
                    "[string, uint, string, float]": ["Tuple[str, int, str, float]",
                                                      "[str, int, str, float]"],
                    "[uint, float]": ["Tuple[int, float]",
                                      "[int, float]"],
                    "[float, boolean, int, int]": ["Tuple[float, bool, int, int]",
                                                   "[float, bool, int, int]"],
                    "[boolean, int]": ["Tuple[bool, int]",
                                       "[bool, int]"],
                    "[string, int]": ["Tuple[str, int]",
                                      "[str, int]"],
                    "[float, int]": ["Tuple[float, int]",
                                     "[float, int]"],
                    "[int, int, string]": ["Tuple[int, int, str]",
                                           "[int, int, str]"],
                    "[timerange, boolean]": ["Tuple[Tuple[float, float], bool]",
                                             "[[ float, float], bool]"],
                    "[string, boolean]": ["Tuple[str, bool]",
                                          "[str, bool]"],
                    "[string, string[]]": ["Tuple[str, List[str]]",
                                           "[str, [str]"],
                    "[boolean, boolean]": ["Tuple[bool, bool]",
                                           "[bool, bool]"],
                    "[boolean, boolean, boolean]": ["Tuple[bool, bool, bool]",
                                                    "[bool, bool, bool]"],
                    "[boolean, boolean, boolean, boolean]": ["Tuple[bool, bool, bool, bool]",
                                                             "[bool, bool, bool, bool]"],
                    "[string, float]": ["Tuple[str, float]",
                                        "[str, float]"],
                    "[string, [, string, ], [, string, ]]": ["Tuple[str, List[str], List[str]]",
                                                             "[str, [str], [str]]"],
                    "[linear, linear, linear, float]": ["Tuple[float, float, float, float]",
                                                        "[float, float, float, float]"],
                    "[int, int, float, float, float]": ["Tuple[int, int, float, float, float]",
                                                        "[int, int, float, float, float]"],
                    "[string, script]": ["Tuple[str, str]",
                                         "[str, str]"],
                    "[script, script]": ["Tuple[str, str]",
                                         "[str, str]"],
                    "[string, string, boolean]": ["Tuple[str, str, bool]",
                                                  "[str, str, bool]"],
                    "[script, string]": ["Tuple[str, str]",
                                         "[str, str]"],
                    "[string, string, int, string]": ["Tuple[str, str, int, str]",
                                                      "[str, str, int, str]"],
                    "[string, string, int]": ["Tuple[str, str, int]",
                                              "[str, str, int]"],
                    "[string, string, int, int]": ["Tuple[str, str, int, int]",
                                                   "[str, str, int, int]"],
                    "[uint, boolean]": ["Tuple[int, bool]",
                                        "[int, bool]"],
                    "[int, int, float]": ["Tuple[int, int, float]",
                                          "[int, int, float]"],
                    "[string, float, float]": ["Tuple[str, float, float]",
                                               "[str, float, float]"],
                    "[int, float, float, float]": ["Tuple[int, float, float, float]",
                                                   "[int, float, float, float]"],
                    "[angle, angle]": ["Tuple[float, float]",
                                       "[float, float]"],
                    "[time, time, float]": ["Tuple[float, float, float]",
                                            "[float, float, float]"],
                    "[string, uint]": ["Tuple[str, int]",
                                       "[str, int]"],
                    "[boolean, string, int]": ["Tuple[bool, str, int]",
                                               "[bool, str, int]"],
                    "[int, [, string, ]]": ["Tuple[int, List[str]]",
                                            "[int, [str]]"],
                    "[string, [, string, ]]": ["Tuple[str, List[str]]",
                                               "[str, [str]]"],
                    "[int, [, int, ]]": ["Tuple[int, List[int]]",
                                         "[int, [int]]"],
                    "[string, int, float]": ["Tuple[str, int, float]",
                                             "[str, int, float]"],
                    "[string, string, script]": ["Tuple[str, str, str]",
                                                 "[str, str, str]"],
                    "[string, float, float, float]": ["Tuple[str, float, float, float]",
                                                      "[str, float, float, float]"],
                    "[string, float, float, float, float]": ["Tuple[str, float, float, float, float]",
                                                             "[str, float, float, float]"],
                    "[string, int, int]": ["Tuple[str, int, int]",
                                           "[str, int, int]"],
                    "[string, int, int, int]": ["Tuple[str, int, int, int]",
                                                "[str, int, int, int]"],
                    "[string, int, int, int, int]": ["Tuple[str, int, int, int, int]",
                                                     "[str, int, int, int, int]"],
                    "[boolean, string, string, string, string]": ["Tuple[bool, str, str, str, str]",
                                                                  "[bool, str, str, str, str]"],
                    "[int, boolean]": ["Tuple[int, bool]",
                                       "[int, bool]"],
                    "[int, boolean, string, string, string, string]": ["Tuple[int, bool, str, str, str, str]",
                                                                       "[int, bool, str, str, str, str]"],
                    "[[, float, float, float, ]]": ["Tuple[List[float]]",
                                                    "[[float]]"],
                    "int64": ["int",
                              "int"],
                    "[linear, linear]": ["Tuple[float, float]",
                                         "[float, float]"],
                    "[int, float]": ["Tuple[int, float]",
                                     "[int, float]"],
                    "[int, float, [, float, float, ]]": ["Tuple[int, float, List[float]]",
                                                         "[int, float, [float, float]]"],
                    "[string, uint, uint, uint, uint]": ["Tuple[str, int, int, int, int]",
                                                         "[str, int, int, int, int]"],
                    "[string, uint, boolean]": ["Tuple[str, int, bool]",
                                                "[str, int, bool]"],
                    "[string, string, uint]": ["Tuple[str, str, int]",
                                               "[str, str, int"],
                    "[boolean, boolean, boolean, boolean, boolean]": ["Tuple[bool, bool, bool, bool, bool]",
                                                                      "[bool, bool, bool, bool, bool]"],
                    "[boolean, boolean, boolean, boolean, boolean, boolean, boolean]": [
                        "Tuple[bool, bool, bool, bool, bool, bool, bool]",
                        "[bool, bool, bool, bool, bool, bool, bool]"],
                    "[int, name]": ["Tuple[int, str]",
                                    "[int, str]"],
                    "int[]": ["List[int]",
                              "[int]"],
                    "[uint, uint, uint, float, float]": ["Tuple[int, int, int, float, float]",
                                                         "[int, int, int, float, float]"],
                    "[linear, linear, linear, linear]": ["Tuple[float, float, float, float]",
                                                         "[float, float, float, float]"],
                    "[time, time, time, time]": ["Tuple[float, float, float, float]",
                                                 "[float, float, float, float]"],
                    "[string, int, string]": ["Tuple[str, int, str]", "[str, int, str]"],
                    "[string, int, float, float, float]": ["Tuple[str, int, float, float, float]",
                                                           "[str, int, float, float, float]"],
                    "[string, int, boolean]": ["Tuple[str, int, bool]",
                                               "[str, int, bool]"],
                    "[int, script]": ["Tuple[int, str]",
                                      "[int, str]"],
                    "[uint, linear]": ["Tuple[int, float]",
                                       "[int, float]"],
                    "[uint, string]": ["Tuple[int, str]",
                                       "[int, str]"],
                    "[linear, linear, linear, linear, linear]": ["Tuple[float, float, float, float, float]",
                                                                 "[float, float, float, float, float]"],
                    "[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float]": [
                        "Tuple[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float]",
                        "[float, float, float, float, float, float, float, float, float, float, float, float, float, float, float, float]"]}

    return lookup_table.get(argument)


def undo_query_edit_to_bools(syntax: str) -> Tuple[bool, bool, bool]:
    """
    This function takes all found permutations of the undo/query/edit block
    and converts the result to a set of booleans pertaining to the undo/query/edit
    ability of the function
    """
    # Remove the name of the command from the passed in syntax
    syntax = " ".join(syntax.lower().split(" ")[1:])

    lookup_table = {'is not undoable, not queryable, and not editable.': (False, False, False),
                    'is undoable, not queryable, and not editable.': (True, False, False),
                    'is undoable, queryable, and editable.': (True, True, True),
                    'is not undoable, queryable, and editable.': (False, True, True),
                    'is undoable, queryable, and not editable.': (True, True, False),
                    'is not undoable, queryable, and not editable.': (False, True, False),
                    'is undoable, not queryable, and editable.': (True, False, True)}

    return lookup_table.get(syntax)
